"""Scaffold autoloop onto a new repository.

Prerequisites:
    - Python 3.13+
    - GitHub CLI (`gh`) installed and authenticated
    - Claude Code CLI (`claude`) installed

Quick start — apply autoloop to your repo:

    1. Clone the autoloop source (temporary, can delete after):
       git clone https://github.com/Sanctum-Origo-Systems/patina.git /tmp/patina

    2. Clone your repo (if not already cloned):
       git clone git@github.com:owner/repo.git ~/projects/repo

    3. Run init from the patina checkout:
       python /tmp/patina/autoloop/init.py \\
           --repo owner/repo \\
           --target ~/projects/repo \\
           --reviewer your-github-username \\
           --verify-command "pytest"

    4. Review and adjust autoloop.toml in your repo
       (models, timeouts, test command, etc.)

    5. Commit the generated files:
       cd ~/projects/repo
       git add autoloop/ autoloop.toml .github/workflows/autoloop-cleanup.yml .gitignore
       git commit -m "feat: add autoloop pipeline"
       git push

    6. Create issues in your repo, then run from the repo root:
       python autoloop/triage_issues.py     # AI-triage open issues
       python autoloop/implement_issue.py   # implement top ready issue

    7. Clean up the temporary clone:
       rm -rf /tmp/patina

Options:
    --dry-run       Preview label commands without creating them
    --skip-labels   Skip GitHub label creation
    --skip-copy     Skip copying autoloop/ scripts (config-only setup)

Creates autoloop.toml, copies autoloop/ scripts, installs GitHub labels,
and adds the CI workflow. Idempotent — safe to re-run.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

AUTOLOOP_DIR = Path(__file__).resolve().parent

COPY_FILES = [
    "__init__.py",
    "config.py",
    "claude_runner.py",
    "auto_close_parent.py",
    "create_issue.py",
    "implement_issue.py",
    "triage_issues.py",
    "update_changelog.py",
]

LABELS = [
    ("ready", "0E8A16", "Triaged and ready for implementation"),
    ("rejected", "D93F0B", "Triaged and rejected"),
    ("needs-decomposition", "FBCA04", "Too large, needs sub-issues"),
    ("in-progress", "1D76DB", "Implementation in progress"),
    ("in-review", "BFD4F2", "PR open, awaiting review"),
    ("needs-human", "D4C5F9", "Blocked, requires human input"),
    ("needs-design", "C2E0C6", "Requires design review before implementation"),
    ("design-required", "C2E0C6", "Issue requires a design doc"),
    ("p0", "B60205", "Critical priority"),
    ("p1", "D93F0B", "High priority"),
    ("p2", "FBCA04", "Normal priority"),
]

TOML_TEMPLATE = """\
# AutoLoop configuration — generated by autoloop init.
# Values here override dataclass defaults; env vars override these.

repo = "{repo}"

# Models
triage_model = "sonnet"
impl_model = "claude-opus-4-6[1m]"

# Timeouts (seconds)
impl_timeout = 900
triage_timeout = 90
test_timeout = 120

# GitHub
pr_reviewer = "{reviewer}"

# Verification
verify_command = "{verify_command}"

# Retry / truncation limits
max_retries = 3
tree_truncation = 3000
diff_truncation = 8000
error_truncation = 2000
spec_truncation = 4000

# Labels that indicate an issue has already been triaged.
# To recreate labels manually:
#   gh label create <name> --repo {repo} --color <color> --description "..."
triage_labels = [
    "ready",
    "rejected",
    "needs-decomposition",
    "in-progress",
    "in-review",
    "needs-human",
]
"""

WORKFLOW_TEMPLATE = """\
name: Autoloop Cleanup
on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  contents: write
  pull-requests: read

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Remove autoloop labels from linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              'ready', 'rejected', 'needs-decomposition',
              'in-progress', 'in-review', 'needs-human',
              'p0', 'p1', 'p2'
            ];
            const body = context.payload.pull_request.body || '';
            const matches = body.match(/Closes #(\\d+)/g) || [];
            for (const match of matches) {{
              const issueNumber = parseInt(match.replace('Closes #', ''));
              for (const label of labels) {{
                try {{
                  await github.rest.issues.removeLabel({{
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    name: label
                  }});
                }} catch (e) {{}}
              }}
            }}

  auto-close-parent:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Auto-close parent issue when last sub-issue completes
        env:
          GH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: python autoloop/auto_close_parent.py "${{{{ github.event.pull_request.number }}}}"
"""

GITIGNORE_ENTRY = "autoloop/run_history.jsonl"


def copy_scripts(target: Path) -> None:
    dest = target / "autoloop"
    dest.mkdir(exist_ok=True)
    for name in COPY_FILES:
        src = AUTOLOOP_DIR / name
        if not src.exists():
            print(f"  skip {name} (not found in source)")
            continue
        shutil.copy2(src, dest / name)
        print(f"  copied {name}")


def write_toml(target: Path, repo: str, reviewer: str, verify_command: str) -> None:
    path = target / "autoloop.toml"
    if path.exists():
        print(f"  autoloop.toml already exists, skipping (delete to regenerate)")
        return
    path.write_text(
        TOML_TEMPLATE.format(repo=repo, reviewer=reviewer, verify_command=verify_command)
    )
    print(f"  created autoloop.toml")


def write_workflow(target: Path) -> None:
    path = target / ".github" / "workflows" / "autoloop-cleanup.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        print(f"  workflow already exists, skipping (delete to regenerate)")
        return
    path.write_text(WORKFLOW_TEMPLATE)
    print(f"  created .github/workflows/autoloop-cleanup.yml")


def update_gitignore(target: Path) -> None:
    path = target / ".gitignore"
    if path.exists():
        content = path.read_text()
        if GITIGNORE_ENTRY in content:
            print(f"  .gitignore already has {GITIGNORE_ENTRY}")
            return
        if not content.endswith("\n"):
            content += "\n"
        content += GITIGNORE_ENTRY + "\n"
        path.write_text(content)
    else:
        path.write_text(GITIGNORE_ENTRY + "\n")
    print(f"  added {GITIGNORE_ENTRY} to .gitignore")


def create_labels(repo: str, dry_run: bool = False) -> None:
    for name, color, description in LABELS:
        cmd = [
            "gh", "label", "create", name,
            "--repo", repo,
            "--color", color,
            "--description", description,
            "--force",
        ]
        if dry_run:
            print(f"  [dry-run] {' '.join(cmd)}")
            continue
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"  created label: {name}")
        else:
            stderr = result.stderr.strip()
            if "already exists" in stderr:
                print(f"  label exists: {name}")
            else:
                print(f"  failed: {name} — {stderr}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold autoloop onto a new repo")
    parser.add_argument("--repo", required=True, help="GitHub owner/repo (e.g. user/project)")
    parser.add_argument("--target", required=True, help="Local path to the target repo")
    parser.add_argument("--reviewer", default="", help="GitHub username for PR reviews")
    parser.add_argument(
        "--verify-command", default="uv run pytest", help="Test command (default: uv run pytest)"
    )
    parser.add_argument("--dry-run", action="store_true", help="Print label commands without running")
    parser.add_argument("--skip-labels", action="store_true", help="Skip GitHub label creation")
    parser.add_argument("--skip-copy", action="store_true", help="Skip copying autoloop/ scripts")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.is_dir():
        print(f"Error: target directory does not exist: {target}")
        sys.exit(1)

    print(f"Initializing autoloop for {args.repo} in {target}\n")

    print("Config:")
    write_toml(target, args.repo, args.reviewer, args.verify_command)

    if not args.skip_copy:
        print("\nScripts:")
        copy_scripts(target)

    print("\nWorkflow:")
    write_workflow(target)

    print("\nGitignore:")
    update_gitignore(target)

    if not args.skip_labels:
        print("\nLabels:")
        create_labels(args.repo, dry_run=args.dry_run)

    print("\nDone! Next steps:")
    print(f"  1. Review autoloop.toml in {target}")
    print(f"  2. Commit the autoloop/ directory and workflow")
    print(f"  3. Run: python autoloop/triage_issues.py  (to triage open issues)")
    print(f"  4. Run: python autoloop/implement_issue.py (to implement top ready issue)")


if __name__ == "__main__":
    main()
